title: UN1CA
description: Work-in-progress custom firmware for Samsung Galaxy devices.
url: "https://unica.mesalabs.io"
permalink: pretty
# Set theme
remote_theme: just-the-docs/just-the-docs
# Set color scheme
color_scheme: dark
# Favicon
favicon_ico: "/assets/images/favicon.ico"
# Logo
logo: "/assets/images/header.png"
# Disable heading anchor links
heading_anchors: false
