# Site settings
title: Aeretrea
description: Work-in-progress custom firmware for Samsung Galaxy devices.
url: "https://aeretrea.github.io/Aeretrea"
repository: Aeretrea/Aeretrea

permalink: pretty

# Set theme
remote_theme: just-the-docs/just-the-docs
# Favicon
favicon_ico: "/Aeretrea/assets/images/favicon.ico"

# Set color scheme
color_scheme: unica

# Set a path/url to a logo that will be displayed instead of the title
logo: "/Aeretrea/assets/images/header.png"

search:
  # Display the relative url in search results
  rel_url: false
  # Enable or disable the search button that appears in the bottom right corner of every page
  button: true

# Enable or disable heading anchors
heading_anchors: false

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "https://github.com/Aeretrea/Aeretrea"

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Coded by BlackMesa123 &copy; 2023. Distributed under the <a href=\"https://github.com/Aeretrea/Aeretrea/tree/fourteen/LICENSE\">GPLv3 license.</a>"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Aeretrea/Aeretrea"
gh_edit_branch: "fourteen"
gh_edit_source: docs
gh_edit_view_mode: "tree"

callouts_level: loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
