name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [a52sxq, m52xq]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: 'recursive'

      - name: Free disk space
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            attr ccache clang file golang \
            libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libusb-1.0-0-dev \
            libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler ninja-build
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.14.1

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Build dependencies
        run: ./scripts/build_dependencies.sh

      - name: Generate build config
        run: source ./buildenv.sh ${{ matrix.target }}

      - name: Download stock firmwares
        run: ./scripts/download_fw.sh

      - name: Extract stock firmwares
        run: |
          ./scripts/extract_fw.sh
          ./scripts/cleanup.sh odin

      - name: Build ROM
        run: ./scripts/make_rom.sh
